{
 "title": "Monitor system",
 "time": { "from": "2022-04-18T00:39:20.694Z", "to": "2022-04-18T03:44:48.892Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Mean平均值",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"MonitorSystem\")\r\n  |> range(start: -5h, stop: -1s)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\" and r[\"_field\"] == \"Mean_X\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield()\r\n"
    },
    {
     "query": "from(bucket: \"MonitorSystem\")\r\n  |> range(start: -5h, stop: -1s)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\" and r[\"_field\"] == \"Mean_Y\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield()\r\n"
    },
    {
     "query": "from(bucket: \"MonitorSystem\")\r\n  |> range(start: -5h, stop: -1s)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\" and r[\"_field\"] == \"Mean_Z\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield()\r\n\r\n"
    }
   ]
  },
  {
   "title": "standard deviation標準差",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"MonitorSystem\")\r\n  |> range(start: -5h, stop: -1s)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\" and r[\"_field\"] == \"Std_X\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield()\r\n"
    },
    {
     "query": "from(bucket: \"MonitorSystem\")\r\n  |> range(start: -5h, stop: -1s)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\" and r[\"_field\"] == \"Std_Y\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield()\r\n\r\n"
    },
    {
     "query": "from(bucket: \"MonitorSystem\")\r\n  |> range(start: -5h, stop: -1s)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\" and r[\"_field\"] == \"Std_Z\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield()\r\n"
    }
   ]
  },
  {
   "title": "Root Mean Square 均方根值",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "accG" } },
   "targets": [
    {
     "query": "from(bucket: \"MonitorSystem\")\r\n  |> range(start: -5h, stop: -1s)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\" and r[\"_field\"] == \"RMS_X\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield()\r\n"
    },
    {
     "query": "from(bucket: \"MonitorSystem\")\r\n  |> range(start: -5h, stop: -1s)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\" and r[\"_field\"] == \"RMS_Y\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield()\r\n"
    },
    {
     "query": "from(bucket: \"MonitorSystem\")\r\n  |> range(start: -5h, stop: -1s)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\" and r[\"_field\"] == \"RMS_Z\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield()\r\n"
    }
   ]
  },
  {
   "title": "Kurtosis 峰度值",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "accG" } },
   "targets": [
    {
     "query": "from(bucket: \"MonitorSystem\")\r\n  |> range(start: -5h, stop: -1s)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\" and r[\"_field\"] == \"Kurtosis_X\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield()\r\n"
    },
    {
     "query": "from(bucket: \"MonitorSystem\")\r\n  |> range(start: -5h, stop: -1s)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\" and r[\"_field\"] == \"Kurtosis_Y\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield()\r\n"
    },
    {
     "query": "from(bucket: \"MonitorSystem\")\r\n  |> range(start: -5h, stop: -1s)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\" and r[\"_field\"] == \"Kurtosis_Z\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield()\r\n"
    }
   ]
  },
  {
   "title": "Total Power 頻譜總功率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"MonitorSystem\")\r\n  |> range(start: -5h, stop: -1s)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\" and r[\"_field\"] == \"tp_X\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield()\r\n"
    },
    {
     "query": "from(bucket: \"MonitorSystem\")\r\n  |> range(start: -5h, stop: -1s)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\" and r[\"_field\"] == \"tp_Y\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield()\r\n"
    },
    {
     "query": "from(bucket: \"MonitorSystem\")\r\n  |> range(start: -5h, stop: -1s)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\" and r[\"_field\"] == \"tp_Z\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield()\r\n"
    }
   ]
  },
  {
   "title": "Peak Frequency 最大主頻",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "query": "from(bucket: \"MonitorSystem\")\r\n  |> range(start: -5h, stop: -1s)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\" and r[\"_field\"] == \"fundamental_freq_X\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield()\r\n"
    },
    {
     "query": "from(bucket: \"MonitorSystem\")\r\n  |> range(start: -5h, stop: -1s)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\" and r[\"_field\"] == \"fundamental_freq_Y\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield()\r\n"
    },
    {
     "query": "from(bucket: \"MonitorSystem\")\r\n  |> range(start: -5h, stop: -1s)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\" and r[\"_field\"] == \"fundamental_freq_Z\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield()\r\n"
    }
   ]
  },
  {
   "title": "single channel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"testDB\")\r\n  |> range(start: -5h, stop: -1s)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\" and r[\"_field\"] == \"ch1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield()\r\n"
    }
   ]
  },
  {
   "title": "Test1",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"MonitorSystem\")\r\n  |> range(start: -5h, stop: -1s)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\" and r[\"_field\"] == \"sensor/0/x/mean\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield()\r\n"
    }
   ]
  }
 ]
}